server:
  port: 8080

sms:
  from-number: [created-sending-number]
  endpoint: https://[endpoint].communication.azure.com
  azure-key-credential: [key-from-communication-service]
  connection-string: [connection-string-for-communication-service]